set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",alacritty:Tc"

# set -g default-terminal "screen-256color"

set -g prefix C-a

set -g mouse on

set -g status on

# Change of indexes
set -g base-index 1
setw -g pane-base-index 1

set-window-option -g mode-keys vi

# Redefine of keys
bind-key | split-window -h

unbind '"'
bind-key - split-window -v -c "#{pane_current_path}"

unbind %
bind-key | split-window -h -c "#{pane_current_path}"

bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key h select-pane -L

bind-key -r m resize-pane -Z

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind-key -T copy-mode-vi MouseDragEnd1Pane


# ================= THEME ================

# TokyoNight colors for Tmux

set -g mode-style "fg=#7aa2f7,bg=#3b4261"

set -g message-style "fg=#7aa2f7,bg=#3b4261"
set -g message-command-style "fg=#7aa2f7,bg=#3b4261"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#7aa2f7,bg=#16161e"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#15161e,bg=#7aa2f7,bold] #S #[fg=#7aa2f7,bg=#16161e,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#7aa2f7,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#15161e,bg=#7aa2f7,bold] #h "
if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" == "24" ]' {
  set -g status-right "#[fg=#7aa2f7,nobold,nounderscore,noitalics]#[fg=#15161e,bg=#7aa2f7,bold] #h "
}

setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=#16161e"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#a9b1d6,bg=#16161e"
setw -g window-status-format "#[fg=#16161e,bg=#16161e,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#16161e,bg=#16161e,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#16161e,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#3b4261,bold] #I  #W #F #[fg=#3b4261,bg=#16161e,nobold,nounderscore,noitalics]"

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#e0af68]#[bg=#16161e]#[fg=#16161e]#[bg=#e0af68]"
set -g @prefix_highlight_output_suffix ""

# ========================================

# Sory by name
#bind-key s choose-tree -sZ -O name

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @resurrect-processes 'ssh psql mysql sqlite3'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# === Tokyo Night ===

# set -g @tokyo-night-tmux_theme 'night'
# set -g @tokyo-night-tmux_transparent 0
# set -g @tokyo-night-tmux_window_id_style none
# set -g @tokyo-night-tmux_pane_id_style none
# set -g @tokyo-night-tmux_zoom_id_style none
# # Icon styles
# set -g @tokyo-night-tmux_terminal_icon 
# set -g @tokyo-night-tmux_active_terminal_icon 
# # No extra spaces between icons
# set -g @tokyo-night-tmux_window_tidy_icons 0
# # Net speed
# set -g @tokyo-night-tmux_show_netspeed 1
# set -g @tokyo-night-tmux_netspeed_iface "wlo1" # Detected via default route
# set -g @tokyo-night-tmux_netspeed_showip 1      # Display IPv4 address (default 0)
# set -g @tokyo-night-tmux_netspeed_refresh 1     # Update interval in seconds (default 1)

# Run of plugin manager
run '~/.tmux/plugins/tpm/tpm'
